name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main  # or the branch you want to trigger on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.138.0'  # Specify the version of Hugo to match your local version

      - name: Install dependencies
        run: |
          # If you have dependencies, add commands here (e.g., npm install)
          echo "No additional dependencies needed"

      - name: Build the site
        run: |
          hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
